-- 004 成功後以 postgres 執行整份。只新增暫時測試資料，全部 ROLLBACK。
-- 使用既有同家庭 A/B 模擬 JWT；不更動 Auth 或任何既有品項／歷史。
begin;
set local lock_timeout='5s';
set local statement_timeout='30s';
do $$
declare
  a uuid; b uuid; h uuid; other_home uuid; it uuid; other_item uuid; source uuid; invalid_source uuid;
  outsider uuid:=gen_random_uuid(); tag text:='__FLOW_TEST_'||gen_random_uuid()::text;
  snap jsonb; before_history jsonb; before_last timestamptz; old_until timestamptz; v bigint; n integer; k integer;
begin
  select ma.user_id,mb.user_id,ma.household_id into a,b,h from public.life_household_members ma
    join public.life_household_members mb on ma.household_id=mb.household_id and ma.user_id<mb.user_id limit 1;
  if a is null then raise exception '需要兩位同家庭成員，未寫入資料'; end if;
  perform set_config('request.jwt.claim.sub',a::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
  set local role authenticated;
  source:=public.restock_save_source(h,null,null,tag||'_store');
  it:=public.restock_add_item_with_sources(h,tag,'浴廁',false,array[source]);
  if not exists(select 1 from public.restock_items where id=it and purchase_quantity=1 and snoozed_until is null) then raise exception 'FAIL default'; end if;
  if not exists(select 1 from public.restock_activity where item_id=it and event='add' and actor_id=a and item_name=tag) then raise exception 'FAIL add actor'; end if;
  begin perform public.restock_set_purchase_quantity(it,1,2); raise exception 'FAIL normal quantity'; exception when invalid_parameter_value then null; end;
  perform public.restock_change_item(it,1,'low');
  select count(*) into n from public.restock_activity where item_id=it;
  perform public.restock_set_purchase_quantity(it,2,2);
  perform public.restock_set_purchase_quantity(it,3,3);
  perform public.restock_set_purchase_quantity(it,4,2);
  if not exists(select 1 from public.restock_items where id=it and purchase_quantity=2 and version=5) then raise exception 'FAIL quantity +/-'; end if;
  if (select count(*) from public.restock_activity where item_id=it)<>n then raise exception 'FAIL quantity activity spam'; end if;
  begin perform public.restock_set_purchase_quantity(it,4,4); raise exception 'FAIL stale quantity'; exception when serialization_failure then null; end;
  begin perform public.restock_set_purchase_quantity(it,null,4); raise exception 'FAIL null version'; exception when serialization_failure then null; end;
  foreach k in array array[0,1000] loop
    begin perform public.restock_set_purchase_quantity(it,5,k); raise exception 'FAIL invalid quantity'; exception when invalid_parameter_value then null; end;
  end loop;
  begin perform public.restock_set_purchase_quantity(it,5,null); raise exception 'FAIL null quantity'; exception when invalid_parameter_value then null; end;
  begin perform public.restock_snooze_item(it,5); raise exception 'FAIL low snooze'; exception when invalid_parameter_value then null; end;
  reset role;
  perform set_config('request.jwt.claim.sub',b::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
  set local role authenticated;
  snap:=public.restock_snapshot();
  if not exists(select 1 from jsonb_array_elements(snap->'items') x where x->>'id'=it::text and (x->>'purchase_quantity')::int=2) then raise exception 'FAIL B quantity sync'; end if;
  if not exists(select 1 from jsonb_array_elements(snap->'activity') x where x->>'item_id'=it::text and x->>'actor_id'=a::text) then raise exception 'FAIL B activity read'; end if;
  perform public.restock_change_item(it,5,'restock');
  if not exists(select 1 from public.restock_items where id=it and status='normal' and purchase_quantity=1 and version=6) then raise exception 'FAIL restock reset'; end if;
  if not exists(select 1 from public.restock_history where item_id=it and purchased_quantity=2 and created_by=b) then raise exception 'FAIL history quantity'; end if;
  if not exists(select 1 from public.restock_activity where item_id=it and event='restock' and actor_id=b and quantity=2) then raise exception 'FAIL restock actor'; end if;
  select jsonb_agg(r order by r.id) into before_history from public.restock_history r where item_id=it;
  select last_restocked_at into before_last from public.restock_items where id=it;
  perform public.restock_snooze_item(it,6);
  select snoozed_until into old_until from public.restock_items where id=it;
  if old_until is null or old_until<clock_timestamp()+interval '6 days 23 hours 59 minutes' or old_until>clock_timestamp()+interval '7 days 10 seconds' then raise exception 'FAIL 7 days'; end if;
  if before_history is distinct from (select jsonb_agg(r order by r.id) from public.restock_history r where item_id=it) then raise exception 'FAIL snooze history'; end if;
  if before_last is distinct from (select last_restocked_at from public.restock_items where id=it) then raise exception 'FAIL snooze last date'; end if;
  begin perform public.restock_snooze_item(it,6); raise exception 'FAIL stale snooze'; exception when serialization_failure then null; end;
  if not exists(select 1 from public.restock_activity where item_id=it and event='snooze' and actor_id=b) then raise exception 'FAIL snooze actor'; end if;
  -- 改名保留 snooze、原 ID、日期、歷史；來源版 RPC 繼續使用同一 version。
  perform public.restock_update_item_with_sources(it,7,tag||'_edited','浴廁',array[source]);
  if not exists(select 1 from public.restock_items where id=it and version=8 and snoozed_until=old_until and last_restocked_at=before_last) then raise exception 'FAIL edit preserve'; end if;
  perform public.restock_change_item(it,8,'low');
  if not exists(select 1 from public.restock_items where id=it and purchase_quantity=1 and snoozed_until is null) then raise exception 'FAIL low clears snooze'; end if;
  perform public.restock_set_purchase_quantity(it,9,4);
  perform public.restock_change_item(it,10,'normal');
  if not exists(select 1 from public.restock_items where id=it and purchase_quantity=1 and version=11) then raise exception 'FAIL cancel reset'; end if;
  -- 舊手機 RPC 保持可用，正常用品直接已補貨仍記 1。
  perform public.restock_change_item(it,11,'restock');
  select version into v from public.restock_items where id=it;
  begin update public.restock_items set purchase_quantity=9 where id=it; raise exception 'FAIL direct update'; exception when insufficient_privilege then null; end;
  begin delete from public.restock_items where id=it; raise exception 'FAIL direct delete'; exception when insufficient_privilege then null; end;
  begin insert into public.restock_activity(household_id,item_id,item_name,actor_id,event) values(h,it,tag,a,'add'); raise exception 'FAIL forged activity'; exception when insufficient_privilege then null; end;
  begin update public.restock_activity set actor_id=a where item_id=it; raise exception 'FAIL activity update'; exception when insufficient_privilege then null; end;
  begin delete from public.restock_activity where item_id=it; raise exception 'FAIL activity delete'; exception when insufficient_privilege then null; end;
  reset role;
  perform set_config('request.jwt.claim.sub',a::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
  set local role authenticated;
  other_home:=public.life_create_household(tag||'_other');
  other_item:=public.restock_add_item(other_home,tag||'_private','其他',true);
  invalid_source:=public.restock_save_source(other_home,null,null,tag||'_private_store');
  select count(*) into n from public.restock_activity where item_id=it;
  begin perform public.restock_update_item_with_sources(it,v,tag||'_invalid','浴廁',array[invalid_source]); raise exception 'FAIL invalid source'; exception when invalid_parameter_value then null; end;
  if (select count(*) from public.restock_activity where item_id=it)<>n then raise exception 'FAIL activity partial commit'; end if;
  -- 超過20筆只回傳最近20筆，依每家庭分開限制。
  for k in 1..21 loop perform public.restock_add_item(other_home,tag||'_limit_'||k,'其他',false); end loop;
  snap:=public.restock_snapshot();
  if (select count(*) from jsonb_array_elements(snap->'activity') x where x->>'household_id'=other_home::text)<>20 then raise exception 'FAIL activity limit'; end if;
  reset role;
  perform set_config('request.jwt.claim.sub',b::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
  set local role authenticated;
  if exists(select 1 from public.restock_activity where household_id=other_home) then raise exception 'FAIL cross activity RLS'; end if;
  snap:=public.restock_snapshot();
  if exists(select 1 from jsonb_array_elements(snap->'activity') x where x->>'household_id'=other_home::text) then raise exception 'FAIL cross snapshot'; end if;
  begin perform public.restock_set_purchase_quantity(other_item,1,2); raise exception 'FAIL cross quantity'; exception when insufficient_privilege then null; end;
  begin perform public.restock_snooze_item(other_item,1); raise exception 'FAIL cross snooze'; exception when insufficient_privilege then null; end;
  begin perform public.restock_update_item(other_item,1,tag,'其他'); raise exception 'FAIL cross edit'; exception when insufficient_privilege then null; end;
  begin perform public.restock_delete_item(other_item,1); raise exception 'FAIL cross archive'; exception when insufficient_privilege then null; end;
  perform public.restock_delete_item(it,v);
  if not exists(select 1 from public.restock_activity where item_id=it and event='archive' and item_name=tag||'_edited' and actor_id=b) then raise exception 'FAIL archive activity'; end if;
  if not exists(select 1 from public.restock_history where item_id=it) then raise exception 'FAIL archive history'; end if;
  if exists(select 1 from jsonb_array_elements(public.restock_snapshot()->'items') x where x->>'id'=it::text) then raise exception 'FAIL archived snapshot'; end if;
  begin perform public.restock_snooze_item(it,v+1); raise exception 'FAIL archived snooze'; exception when serialization_failure then null; end;
  begin perform public.restock_set_purchase_quantity(it,v+1,2); raise exception 'FAIL archived quantity'; exception when serialization_failure then null; end;
  reset role;
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider,'role','authenticated')::text,true);
  set local role authenticated;
  if exists(select 1 from public.restock_activity) then raise exception 'FAIL outsider read'; end if;
  begin perform public.restock_snooze_item(other_item,1); raise exception 'FAIL outsider snooze'; exception when insufficient_privilege then null; end;
  begin perform public.restock_set_purchase_quantity(other_item,1,2); raise exception 'FAIL outsider quantity'; exception when insufficient_privilege then null; end;
  reset role;
  perform set_config('request.jwt.claim.sub','',true);
  perform set_config('request.jwt.claims','{}',true);
  set local role anon;
  begin perform public.restock_snapshot(); raise exception 'FAIL anon snapshot'; exception when insufficient_privilege then null; end;
  begin perform public.restock_set_purchase_quantity(other_item,1,2); raise exception 'FAIL anon quantity'; exception when insufficient_privilege then null; end;
  begin perform public.restock_snooze_item(other_item,1); raise exception 'FAIL anon snooze'; exception when insufficient_privilege then null; end;
  begin perform 1 from public.restock_activity; raise exception 'FAIL anon activity'; exception when insufficient_privilege then null; end;
  reset role;
  raise notice 'PASS: 待購數量、還很多、動態及隔離回歸通過；測試資料全部回滾';
end;
$$;
rollback;
